// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSI2CmtEgAkvDXep6ZSxUfOMeffMkbZE4',
    appId: '1:1077724702640:web:deebe3450120df74c69875',
    messagingSenderId: '1077724702640',
    projectId: 'loginauthtutorial-f64b3',
    authDomain: 'loginauthtutorial-f64b3.firebaseapp.com',
    storageBucket: 'loginauthtutorial-f64b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFJ9z20DGSzYoOV173NRtooudoWZciUc',
    appId: '1:1077724702640:android:f92f25b7354c9035c69875',
    messagingSenderId: '1077724702640',
    projectId: 'loginauthtutorial-f64b3',
    storageBucket: 'loginauthtutorial-f64b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EmYbTBYe9KAQeDsufFcgTLq1aX0cuOQ',
    appId: '1:1077724702640:ios:26d866e2ebdbc1b7c69875',
    messagingSenderId: '1077724702640',
    projectId: 'loginauthtutorial-f64b3',
    storageBucket: 'loginauthtutorial-f64b3.appspot.com',
    iosBundleId: 'com.example.loginauthh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9EmYbTBYe9KAQeDsufFcgTLq1aX0cuOQ',
    appId: '1:1077724702640:ios:26d866e2ebdbc1b7c69875',
    messagingSenderId: '1077724702640',
    projectId: 'loginauthtutorial-f64b3',
    storageBucket: 'loginauthtutorial-f64b3.appspot.com',
    iosBundleId: 'com.example.loginauthh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSI2CmtEgAkvDXep6ZSxUfOMeffMkbZE4',
    appId: '1:1077724702640:web:4632e2ac366e5550c69875',
    messagingSenderId: '1077724702640',
    projectId: 'loginauthtutorial-f64b3',
    authDomain: 'loginauthtutorial-f64b3.firebaseapp.com',
    storageBucket: 'loginauthtutorial-f64b3.appspot.com',
  );
}
